var nameTable = new Names();
nameTable.add("boneblock", "boneBlock");
nameTable.add("boneore", "boneOre");
nameTable.add("bonebrick", "boneBrick");
nameTable.add("bonewall", "boneWall");
nameTable.add("glowbone", "glowBone");
nameTable.add("twilicornsword", "twilicornSword");
nameTable.add("twilicornpick", "twilicornPick");
nameTable.add("twilicornhoe", "twilicornHoe");
nameTable.add("twilicornaxe", "twilicornAxe");
nameTable.add("twilicornspade", "twilicornSpade");
nameTable.add("twilicornitem", "twilicornItem");
nameTable.add("bowserbone", "bowserBone");
nameTable.add("bowsereye", "bowserEye");
nameTable.add("bonehelmet", "boneHelmet");
nameTable.add("bonechest", "boneChest");
nameTable.add("bonelegs", "boneLegs");
nameTable.add("boneboots", "boneBoots");
nameTable.add("bonesword", "boneSword");
nameTable.add("lunaeclipse", "lunaEclipse");
nameTable.add("bonepick", "bonepick");
nameTable.add("boneaxe", "boneaxe");
nameTable.add("bonehoe", "bonehoe");
nameTable.add("bonespade", "bonespade");
nameTable.add("boneitem", "boneItem");
nameTable.add("twilicornhelmet", "twilicornHelmet");
nameTable.add("twilicornchest", "twilicornChest");
nameTable.add("twilicornlegs", "twilicornLegs");
nameTable.add("twilicornboots", "twilicornBoots");
nameTable.add("twilicornbow", "twilicornBow");
nameTable.add("darkhelmet", "darkHelmet");
nameTable.add("darkchest", "darkChest");
nameTable.add("darklegs", "darkLegs");
nameTable.add("darkboots", "darkBoots");
nameTable.add("twilightstar", "twilightStar");
nameTable.add("yoshisword", "yoshiSword");
nameTable.add("lightningcloud", "lightningCloud");
nameTable.add("diamondgems", "diamondGems");
nameTable.add("butterflies", "butterFlies");
nameTable.add("apples", "apples");
nameTable.add("ballons", "ballons");
nameTable.add("dashmeat", "dashMeat");
nameTable.add("twimeat", "twiMeat");
nameTable.add("applehelmet", "appleHelmet");
nameTable.add("applechest", "appleChest");
nameTable.add("applelegs", "appleLegs");
nameTable.add("appleboots", "appleBoots");
nameTable.add("bearhelmet", "bearHelmet");
nameTable.add("bearchest", "bearChest");
nameTable.add("bearlegs", "bearLegs");
nameTable.add("bearboots", "bearBoots");
nameTable.add("phoenixbow", "phoenixBow");
nameTable.add("applesword", "appleSword");
nameTable.add("applepick", "applePick");
nameTable.add("applehoe", "appleHoe");
nameTable.add("appleaxe", "appleAxe");
nameTable.add("applespade", "appleSpade");
nameTable.add("bearsword", "bearSword");
nameTable.add("bearpick", "bearPick");
nameTable.add("bearhoe", "bearHoe");
nameTable.add("bearaxe", "bearAxe");
nameTable.add("bearspade", "bearSpade");
nameTable.add("friendship", "friendShip");
nameTable.add("mavisorb", "mavisOrb");
nameTable.add("eggtwilightmob", "eggTwilightMob");
nameTable.add("eggmyself", "eggMyself");
nameTable.add("eggcroc", "eggCroc");
nameTable.add("egggiantchick", "eggGiantChick");
nameTable.add("eggchuddymoron", "eggChuddyMoron");
nameTable.add("eggdemonspider", "eggDemonSpider");
nameTable.add("eggleviathan", "eggLeviathan");
nameTable.add("eggkingbowser", "eggKingbowser");
nameTable.add("eggcentipede", "eggCentipede");
nameTable.add("egghydra", "eggHydra");
nameTable.add("eggwindigo", "eggWindigo");
nameTable.add("eggmoose", "eggMoose");
nameTable.add("eggbuffalo", "eggBuffalo");
nameTable.add("eggpowerorb", "eggPowerOrb");
nameTable.add("eggflamedragon", "eggFlameDragon");
nameTable.add("eggmoosebig", "eggMooseBig");
nameTable.add("eggbear", "eggBear");
nameTable.add("eggtoughguy", "eggToughGuy");
nameTable.add("eggmavis", "eggMavis");
nameTable.add("eggursamajor", "eggUrsaMAJOR");
nameTable.add("eggdash", "eggDash");
nameTable.add("eggmanticore", "eggManticore");
nameTable.add("dashsword", "dashSword");
nameTable.add("bearfur", "bearFur");
nameTable.add("beartooth", "bearTooth");
nameTable.add("phoenixfeather", "phoenixFeather");
nameTable.add("cragscale", "cragScale");
nameTable.add("craghammer", "cragHammer");
nameTable.add("cragrainbowcentipede", "cragRainbowCentipede");
nameTable.add("twilicornbone", "twilicornBone");
nameTable.add("eggaj", "eggAj");
nameTable.add("eggscorpion", "eggScorpion");
nameTable.add("darkcrystal", "darkCrystal");
nameTable.add("alicornsword", "alicornSword");
nameTable.add("eggtimberwolf", "eggTimberWolf");
nameTable.add("eggparasprite", "eggParasprite");
nameTable.add("stinger", "stinger");
nameTable.add("eggtmagic", "eggTMagic");
nameTable.add("eggcock", "eggCock");
nameTable.add("unstableitem", "unstableItem");
nameTable.add("dagger", "dagger");
nameTable.add("digger", "digger");
nameTable.add("eggcrabzilla", "eggCrabzilla");
nameTable.add("eggminotaur", "eggMinotaur");
nameTable.add("derpmuffin", "derpMuffin");
nameTable.add("cupcakes", "cupCakes");
nameTable.add("rainbow", "rainbow");
nameTable.add("antenna", "antenna");
nameTable.add("ajsword", "ajSword");
nameTable.add("ajpick", "ajPick");
nameTable.add("ajhoe", "ajHoe");
nameTable.add("ajaxe", "ajAxe");
nameTable.add("ajspade", "ajSpade");
nameTable.add("ajhelmet", "ajHelmet");
nameTable.add("ajchest", "ajChest");
nameTable.add("ajlegs", "ajLegs");
nameTable.add("ajboots", "ajBoots");
nameTable.add("hardapple", "hardApple");
nameTable.add("eggrdcloud", "eggrdCloud");
nameTable.add("rdhelmet", "rdHelmet");
nameTable.add("rdchest", "rdChest");
nameTable.add("rdlegs", "rdLegs");
nameTable.add("rdboots", "rdBoots");
nameTable.add("auroragem", "auroraGem");
nameTable.add("crystalsword", "crystalSword");
nameTable.add("ursaclaws", "ursaClaws");
nameTable.add("eggskullboss", "eggSkullBoss");
nameTable.add("eggskull", "eggSkull");
nameTable.add("dirtsword", "dirtSword");
nameTable.add("yakhorn", "yakHorn");
nameTable.add("eggyakprince", "eggYakPrince");
nameTable.add("eggspikey", "eggSpikey");
nameTable.add("eggrhino", "eggRhino");
nameTable.add("rhinohorn", "rhinoHorn");
nameTable.add("skull", "Skull");
nameTable.add("skullboss", "SkullBoss");
nameTable.add("leviathan", "Leviathan");
nameTable.add("thunderhooves", "ThunderHooves");
nameTable.add("twilicorn", "Twilicorn");
nameTable.add("kingbowser", "Kingbowser");
nameTable.add("centipede", "Centipede");
nameTable.add("mlphydra", "MLPHydra");
nameTable.add("windigo", "Windigo");
nameTable.add("moose", "Moose");
nameTable.add("mlpbuffalo", "MLPBuffalo");
nameTable.add("darkness", "Darkness");
nameTable.add("flamedragon", "FlameDragon");
nameTable.add("moosebig", "MooseBig");
nameTable.add("cragadile", "Cragadile");
nameTable.add("bear", "Bear");
nameTable.add("toughguy", "ToughGuy");
nameTable.add("mavis", "Mavis");
nameTable.add("ursamajor", "UrsaMAJOR");
nameTable.add("phoenix", "Phoenix");
nameTable.add("dash", "Dash");
nameTable.add("manticore", "Manticore");
nameTable.add("rainbowcentipede", "RainbowCentipede");
nameTable.add("aj", "AJ");
nameTable.add("arcticscorpion", "ArcticScorpion");
nameTable.add("timberwolf", "TimberWolf");
nameTable.add("parasprite", "Parasprite");
nameTable.add("twilightmagic", "TwilightMagic");
nameTable.add("cockatrice", "Cockatrice");
nameTable.add("ironwill", "IronWill");
nameTable.add("crabzilla", "Crabzilla");
nameTable.add("dashcloud", "DashCloud");

var createMob = function(name){
	var n = nameTable.lookup(name);
	if (n != null)
		return worldedit.createMob(n, 'My');
	return null;
};

var createItem = function(name){
	var n = nameTable.lookup(name);
	if (n != null)
		return worldedit.createItem(n, 'MLPMod');
	return null;
};

var createBlock = function(name){
	var n = nameTable.lookup(name);
	if (n != null)
		return worldedit.createBlock(n, 'MLPMod');
	return null;
};


exports.createMob = createMob;
exports.createItem = createItem;
exports.createBlock = createBlock;
