importPackage(Packages.com.gaiakeeper.minecraftjs);

importPackage(Packages.twilightsparkle.basic);
importPackage(Packages.twilightsparkle.basic.mob);

exports.createMob = function(name){
	var mob = null;
	switch(name.toLowerCase().split(' ').join('')){
		case 'aj': mob = new Mob(new MyAJ(worldedit.getWorld())); break;
		case 'arcticscorpion': mob = new Mob(new MyArcticScorpion(worldedit.getWorld())); break;
		case 'bear': mob = new Mob(new MyBear(worldedit.getWorld())); break;
		case 'centipede': mob = new Mob(new MyCentipede(worldedit.getWorld())); break;
		case 'cloud': mob = new Mob(new MyCloud(worldedit.getWorld())); break;
		case 'cockatrice': mob = new Mob(new MyCockatrice(worldedit.getWorld())); break;
		case 'crabzilla': mob = new Mob(new MyCrabzilla(worldedit.getWorld())); break;
		case 'cragadile': mob = new Mob(new MyCragadile(worldedit.getWorld())); break;
		case 'darkness': mob = new Mob(new MyDarkness(worldedit.getWorld())); break;
		case 'dash': mob = new Mob(new MyDash(worldedit.getWorld())); break;
		case 'dashcloud': mob = new Mob(new MyDashCloud(worldedit.getWorld())); break;
		case 'flamedragon': mob = new Mob(new MyFlameDragon(worldedit.getWorld())); break;
		case 'ironwill': mob = new Mob(new MyIronWill(worldedit.getWorld())); break;
		case 'kingbowser': mob = new Mob(new MyKingbowser(worldedit.getWorld())); break;
		case 'largeflame': mob = new Mob(new MyLargeFlame(worldedit.getWorld())); break;
		case 'leviathan': mob = new Mob(new MyLeviathan(worldedit.getWorld())); break;
		case 'manticore': mob = new Mob(new MyManticore(worldedit.getWorld())); break;
		case 'mavis': mob = new Mob(new MyMavis(worldedit.getWorld())); break;
		case 'buffalo': mob = new Mob(new MyMLPBuffalo(worldedit.getWorld())); break;
		case 'mlpbuffalo': mob = new Mob(new MyMLPBuffalo(worldedit.getWorld())); break;
		case 'hydra': mob = new Mob(new MyMLPHydra(worldedit.getWorld())); break;
		case 'mlphydra': mob = new Mob(new MyMLPHydra(worldedit.getWorld())); break;
		case 'moose': mob = new Mob(new MyMoose(worldedit.getWorld())); break;
		case 'moosebig': mob = new Mob(new MyMooseBig(worldedit.getWorld())); break;
		case 'parasprite': mob = new Mob(new MyParasprite(worldedit.getWorld())); break;
		case 'phoenix': mob = new Mob(new MyPhoenix(worldedit.getWorld())); break;
		case 'powerorbs': mob = new Mob(new MyPowerOrbs(worldedit.getWorld())); break;
		case 'rainbowcentipede': mob = new Mob(new MyRainbowCentipede(worldedit.getWorld())); break;
		case 'rhinoceros': mob = new Mob(new MyRhinoceros(worldedit.getWorld())); break;
		case 'skull': mob = new Mob(new MySkull(worldedit.getWorld())); break;
		case 'skullboss': mob = new Mob(new MySkullBoss(worldedit.getWorld())); break;
		case 'spikezilla': mob = new Mob(new MySpikezilla(worldedit.getWorld())); break;
		case 'thunderhooves': mob = new Mob(new MyThunderHooves(worldedit.getWorld())); break;
		case 'timberwolf': mob = new Mob(new MyTimberWolf(worldedit.getWorld())); break;
		case 'toughguy': mob = new Mob(new MyToughGuy(worldedit.getWorld())); break;
		case 'twilicorn': mob = new Mob(new MyTwilicorn(worldedit.getWorld())); break;
		case 'twilightmagic': mob = new Mob(new MyTwilightMagic(worldedit.getWorld())); break;
		case 'twilightstar': mob = new Mob(new MyTwilightStar(worldedit.getWorld())); break;
		case 'ursa': mob = new Mob(new MyUrsaMAJOR(worldedit.getWorld())); break;
		case 'ursamajor': mob = new Mob(new MyUrsaMAJOR(worldedit.getWorld())); break;
		case 'windigo': mob = new Mob(new MyWindigo(worldedit.getWorld())); break;
		case 'yakprince': mob = new Mob(new MyYakPrince(worldedit.getWorld())); break;
	}

	return mob;
};

exports.createItem = function(name){
	var item = null;

	switch(name.toLowerCase().split(' ').join('')){
		case 'twilicornsword': item = worldedit.createItem(5184); break;
		case 'twilicornpick': item = worldedit.createItem(5185); break;
		case 'twilicornhoe': item = worldedit.createItem(5186); break;
		case 'twilicornaxe': item = worldedit.createItem(5187); break;
		case 'twilicornspade': item = worldedit.createItem(5188); break;
		case 'twilicornitem': item = worldedit.createItem(5189); break;
		case 'bowserbone': item = worldedit.createItem(5190); break;
		case 'bowsereye': item = worldedit.createItem(5191); break;
		case 'bonehelmet': item = worldedit.createItem(5192); break;
		case 'bonechest': item = worldedit.createItem(5193); break;
		case 'bonelegs': item = worldedit.createItem(5194); break;
		case 'boneboots': item = worldedit.createItem(5195); break;
		case 'bonesword': item = worldedit.createItem(5196); break;
		case 'lunaeclipse': item = worldedit.createItem(5197); break;
		case 'bonepick': item = worldedit.createItem(5198); break;
		case 'boneaxe': item = worldedit.createItem(5199); break;
		case 'bonehoe': item = worldedit.createItem(5200); break;
		case 'bonespade': item = worldedit.createItem(5201); break;
		case 'boneitem': item = worldedit.createItem(5202); break;
		case 'twilicornhelmet': item = worldedit.createItem(5203); break;
		case 'twilicornchest': item = worldedit.createItem(5204); break;
		case 'twilicornlegs': item = worldedit.createItem(5205); break;
		case 'twilicornboots': item = worldedit.createItem(5206); break;
		case 'twilicornbow': item = worldedit.createItem(5207); break;
		case 'darkhelmet': item = worldedit.createItem(5208); break;
		case 'darkchest': item = worldedit.createItem(5209); break;
		case 'darklegs': item = worldedit.createItem(5210); break;
		case 'darkboots': item = worldedit.createItem(5211); break;
		case 'twilightstar': item = worldedit.createItem(5212); break;
		case 'yoshisword': item = worldedit.createItem(5213); break;
		case 'lightningcloud': item = worldedit.createItem(5214); break;
		case 'diamondgems': item = worldedit.createItem(5215); break;
		case 'butterflies': item = worldedit.createItem(5216); break;
		case 'apples': item = worldedit.createItem(5217); break;
		case 'ballons': item = worldedit.createItem(5218); break;
		case 'dashmeat': item = worldedit.createItem(5219); break;
		case 'twimeat': item = worldedit.createItem(5220); break;
		case 'applehelmet': item = worldedit.createItem(5221); break;
		case 'applechest': item = worldedit.createItem(5222); break;
		case 'applelegs': item = worldedit.createItem(5223); break;
		case 'appleboots': item = worldedit.createItem(5224); break;
		case 'bearhelmet': item = worldedit.createItem(5225); break;
		case 'bearchest': item = worldedit.createItem(5226); break;
		case 'bearlegs': item = worldedit.createItem(5227); break;
		case 'bearboots': item = worldedit.createItem(5228); break;
		case 'phoenixbow': item = worldedit.createItem(5229); break;
		case 'applesword': item = worldedit.createItem(5230); break;
		case 'applepick': item = worldedit.createItem(5231); break;
		case 'applehoe': item = worldedit.createItem(5232); break;
		case 'appleaxe': item = worldedit.createItem(5233); break;
		case 'applespade': item = worldedit.createItem(5234); break;
		case 'bearsword': item = worldedit.createItem(5235); break;
		case 'bearpick': item = worldedit.createItem(5236); break;
		case 'bearhoe': item = worldedit.createItem(5237); break;
		case 'bearaxe': item = worldedit.createItem(5238); break;
		case 'bearspade': item = worldedit.createItem(5239); break;
		case 'friendship': item = worldedit.createItem(5240); break;
		case 'mavisorb': item = worldedit.createItem(5241); break;
		case 'eggtwilightmob': item = worldedit.createItem(5242); break;
		case 'eggmyself': item = worldedit.createItem(5243); break;
		case 'eggcroc': item = worldedit.createItem(5244); break;
		case 'egggiantchick': item = worldedit.createItem(5245); break;
		case 'eggchuddymoron': item = worldedit.createItem(5246); break;
		case 'eggdemonspider': item = worldedit.createItem(5247); break;
		case 'eggleviathan': item = worldedit.createItem(5248); break;
		case 'eggkingbowser': item = worldedit.createItem(5249); break;
		case 'eggcentipede': item = worldedit.createItem(5250); break;
		case 'egghydra': item = worldedit.createItem(5251); break;
		case 'eggwindigo': item = worldedit.createItem(5252); break;
		case 'eggmoose': item = worldedit.createItem(5253); break;
		case 'eggbuffalo': item = worldedit.createItem(5254); break;
		case 'eggpowerorb': item = worldedit.createItem(5255); break;
		case 'eggflamedragon': item = worldedit.createItem(5256); break;
		case 'eggmoosebig': item = worldedit.createItem(5257); break;
		case 'eggbear': item = worldedit.createItem(5258); break;
		case 'eggtoughguy': item = worldedit.createItem(5259); break;
		case 'eggmavis': item = worldedit.createItem(5260); break;
		case 'eggursamajor': item = worldedit.createItem(5261); break;
		case 'eggdash': item = worldedit.createItem(5262); break;
		case 'eggmanticore': item = worldedit.createItem(5263); break;
		case 'dashsword': item = worldedit.createItem(5264); break;
		case 'bearfur': item = worldedit.createItem(5265); break;
		case 'beartooth': item = worldedit.createItem(5266); break;
		case 'phoenixfeather': item = worldedit.createItem(5267); break;
		case 'cragscale': item = worldedit.createItem(5268); break;
		case 'craghammer': item = worldedit.createItem(5269); break;
		case 'cragrainbowcentipede': item = worldedit.createItem(5270); break;
		case 'twilicornbone': item = worldedit.createItem(5271); break;
		case 'eggaj': item = worldedit.createItem(5272); break;
		case 'eggscorpion': item = worldedit.createItem(5273); break;
		case 'darkcrystal': item = worldedit.createItem(5274); break;
		case 'alicornsword': item = worldedit.createItem(5275); break;
		case 'eggtimberwolf': item = worldedit.createItem(5276); break;
		case 'eggparasprite': item = worldedit.createItem(5277); break;
		case 'stinger': item = worldedit.createItem(5278); break;
		case 'eggtmagic': item = worldedit.createItem(5279); break;
		case 'eggcock': item = worldedit.createItem(5280); break;
		case 'unstableitem': item = worldedit.createItem(5281); break;
		case 'dagger': item = worldedit.createItem(5282); break;
		case 'digger': item = worldedit.createItem(5283); break;
		case 'eggcrabzilla': item = worldedit.createItem(5284); break;
		case 'eggminotaur': item = worldedit.createItem(5285); break;
		case 'derpmuffin': item = worldedit.createItem(5286); break;
		case 'cupcakes': item = worldedit.createItem(5287); break;
		case 'rainbow': item = worldedit.createItem(5288); break;
		case 'antenna': item = worldedit.createItem(5289); break;
		case 'ajsword': item = worldedit.createItem(5290); break;
		case 'ajpick': item = worldedit.createItem(5291); break;
		case 'ajhoe': item = worldedit.createItem(5292); break;
		case 'ajaxe': item = worldedit.createItem(5293); break;
		case 'ajspade': item = worldedit.createItem(5294); break;
		case 'ajhelmet': item = worldedit.createItem(5295); break;
		case 'ajchest': item = worldedit.createItem(5296); break;
		case 'ajlegs': item = worldedit.createItem(5297); break;
		case 'ajboots': item = worldedit.createItem(5298); break;
		case 'hardapple': item = worldedit.createItem(5299); break;
		case 'eggrdcloud': item = worldedit.createItem(5300); break;
		case 'rdhelmet': item = worldedit.createItem(5301); break;
		case 'rdchest': item = worldedit.createItem(5302); break;
		case 'rdlegs': item = worldedit.createItem(5303); break;
		case 'rdboots': item = worldedit.createItem(5304); break;
		case 'auroragem': item = worldedit.createItem(5305); break;
		case 'crystalsword': item = worldedit.createItem(5306); break;
		case 'ursaclaws': item = worldedit.createItem(5307); break;
		case 'eggskullboss': item = worldedit.createItem(5308); break;
		case 'eggskull': item = worldedit.createItem(5309); break;
		case 'dirtsword': item = worldedit.createItem(5310); break;
		case 'yakhorn': item = worldedit.createItem(5311); break;
		case 'eggyakprince': item = worldedit.createItem(5312); break;
		case 'eggspikey': item = worldedit.createItem(5313); break;
		case 'eggrhino': item = worldedit.createItem(5314); break;
	}

	return item;
};

exports.createBlock = function(name){
	var block = null;

	switch(name.toLowerCase().split(' ').join('')){
		case 'boneblock': block = worldedit.createBlock(212); break;
		case 'boneore': block = worldedit.createBlock(213); break;
		case 'bonebrick': block = worldedit.createBlock(214); break;
		case 'bonewall': block = worldedit.createBlock(215); break;
		case 'glowbone': block = worldedit.createBlock(216); break;
		case 'robotblock': block = worldedit.createBlock(217); break;
		case 'phoenixblock': block = worldedit.createBlock(218); break;
		case 'twilicornblock': block = worldedit.createBlock(219); break;
		case 'bearfurblock': block = worldedit.createBlock(220); break;
		case 'appleblock': block = worldedit.createBlock(221); break;
		case 'arcticblock': block = worldedit.createBlock(222); break;
		case 'hardappleblock': block = worldedit.createBlock(223); break;
		case 'crystalore': block = worldedit.createBlock(224); break;
		case 'crystalblock': block = worldedit.createBlock(225); break;
	}

	return block;
};
